#!/usr/bin/env bash

# Load the shell dotfiles
for file in ~/.{exports,aliases,prompt}; do
	# shellcheck disable=SC1090
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Only run this if we are in a bash shell, not in a zsh
if [ -z "${BASH_VERSION}" ]; then
        # $BASH is not set, therefore we are probably in a csh
        echo "We are not in a bash"
else
	# We are in a bash
	# Case-insensitive globbing (used in pathname expansion)
	shopt -s nocaseglob

	# Append to the Bash history file, rather than overwriting it
	shopt -s histappend

	# Autocorrect typos in path names when using `cd`
	shopt -s cdspell
fi

# rbenv lazy initialization
_rbenv_loaded=0

_init_rbenv() {
  if [ $_rbenv_loaded -eq 0 ]; then
    eval "$(rbenv init -)"
    _rbenv_loaded=1
  fi
}

rbenv() {
  _init_rbenv
  command rbenv "$@"
}

# pyenv is already initialized in exports via pyenv init --path
