#!/usr/bin/env bash

# Cache brew prefix to avoid multiple subshell calls
# NOTE: brew --prefix can hang, so we'll initialize this lazily if needed
# shellcheck disable=SC2155
# export _BREW_PREFIX=$(brew --prefix)

# Make sure pyenv is initialized first for PATH ordering
# eval "$(pyenv init --path)"

# show current dir in iTerm tab title
# source: https://gist.github.com/phette23/5270658
if [ "$ITERM_SESSION_ID" ]; then
  export PROMPT_COMMAND='echo -ne "\033];${PWD##*/}\007"; ':"$PROMPT_COMMAND";
fi

# prompt
#export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
#export CLICOLOR=1
#
# That was my old prompt. My current prompt is defined in ``.prompt``.

# ls
export LSCOLORS=ExFxBxDxCxegedabagacad

# node
# NVM is now initialized in .zshrc to ensure proper PATH ordering
# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY=~/.node_history;
# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768';
# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE='sloppy';
export PATH="$PATH:./node_modules/.bin"

# brew related
export HOMEBREW_CASK_OPTS="--appdir=/Applications --fontdir=/Library/Fonts --qlplugindir=/Library/QuickLook"
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

# Add Homebrew paths (using standard locations to avoid expensive brew --prefix calls)
if [ -d /opt/homebrew ]; then
  export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
  export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:${PATH}"
else
  export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
  export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}"
fi

# Make nano the default editor.
export EDITOR='nano';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';
export HISTTIMEFORMAT="%Y-%m-%d %T "

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';
export LC_CTYPE=en_US.UTF-8;

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# ruby - Use standard Homebrew locations to avoid hanging brew --prefix calls
export optflags="-Wno-error=implicit-function-declaration"
export CFLAGS="-Wno-error=implicit-function-declaration"
if [ -d /opt/homebrew ]; then
  _BREW_OPT=/opt/homebrew/opt
else
  _BREW_OPT=/usr/local/opt
fi
export LDFLAGS="-L$_BREW_OPT/libffi/lib -L$_BREW_OPT/jemalloc/lib $LDFLAGS"
export CPPFLAGS="-I$_BREW_OPT/libffi/include -I$_BREW_OPT/jemalloc/include $CPPFLAGS"
export PKG_CONFIG_PATH="$_BREW_OPT/libffi/lib/pkgconfig:$PKG_CONFIG_PATH"
export CONFIGURE_OPTS="--with-openssl-dir=$_BREW_OPT/openssl@3"

# ruby-build
# Since we are using ruby 3.1 or higher we need to use openssl@3
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$_BREW_OPT/openssl@3 --with-readline-dir=$_BREW_OPT/readline --with-libyaml-dir=$_BREW_OPT/libyaml --with-zlib-dir=$_BREW_OPT/zlib"

# ruby - readline needs this
export LDFLAGS="-L$_BREW_OPT/readline/lib $LDFLAGS"
export CPPFLAGS="-I$_BREW_OPT/readline/include $CPPFLAGS"
export PKG_CONFIG_PATH="$_BREW_OPT/readline/lib/pkgconfig:$PKG_CONFIG_PATH"

# ruby  - openssl needs this
export LDFLAGS="-L$_BREW_OPT/openssl@1.1/lib $LDFLAGS"
export CPPFLAGS="-I$_BREW_OPT/openssl@1.1/include $CPPFLAGS"
export PKG_CONFIG_PATH="$_BREW_OPT/openssl@1.1/lib/pkgconfig:$PKG_CONFIG_PATH"
export PATH="$_BREW_OPT/openssl@1.1/bin:$PATH"

#pyenv for python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
# NOTE: pyenv init --path hangs on this system, disabled for now
# eval "$(pyenv init --path)"

# postgres
export PATH="$_BREW_OPT/postgresql@15/bin:$PATH"
export LDFLAGS="-L$_BREW_OPT/postgresql@15/lib $LDFLAGS"
export CPPFLAGS="-I$_BREW_OPT/postgresql@15/include $CPPFLAGS"
export PKG_CONFIG_PATH="$_BREW_OPT/postgresql@15/lib/pkgconfig"
# libpq
export PATH="$_BREW_OPT/libpq/bin:$PATH"
export LDFLAGS="-L$_BREW_OPT/libpq/lib"
export CPPFLAGS="-I$_BREW_OPT/libpq/include"
export PKG_CONFIG_PATH="$_BREW_OPT/libpq/lib/pkgconfig"

# Fix Ansible
export ANSIBLE_PYTHON_INTERPRETER="$(which python)"

# Add `~/bin` and `.bin` to the `$PATH`
export PATH=${HOME}/bin:${PATH}
export PATH=${HOME}/.bin:${PATH}

# remove duplicate PATH entries (commented out as it causes hangs)
# and finally export one last time
# export PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++{if (NR > 1) printf ORS; printf $a[$1]}')

# dump your path like this
# echo $PATH | tr ':' '\n'. | sort

# Remove annoying warning that I should switch to zsh
# https://support.apple.com/en-us/HT208050
export BASH_SILENCE_DEPRECATION_WARNING=1

# Needed for GPG and e.g. signing commits
# Only set if in an interactive terminal
if [[ -t 0 ]]; then
  export GPG_TTY=$(tty)
fi

# format `time` output in zsh
export TIMEFMT=$'\nTIME NEEDED:\nreal\t%E\nuser\t%U\nsys\t%S'

# Needed for 1Password SSH Agent
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
