#!/usr/bin/env bash

# Color codes:
# - green: time (green in zsh, ANSI 32m in bash)
# - 39: path (light blue, 256-color code 39)
# - red: git branch (red in zsh, ANSI 31m in bash)

# Parse git branch and set color
git_branch() {
	if git rev-parse --git-dir > /dev/null 2>&1; then
		echo " $(git rev-parse --abbrev-ref HEAD)"
	fi
}

# Set prompt based on shell type
if [ -n "${ZSH_VERSION}" ]; then
	# We are in zsh
	# Green time, cyan path, red git branch
	setopt PROMPT_SUBST
	export PS1="%F{green}%*%f %F{39}%~%f%F{red}%(1j..)\$(git_branch)%f $ "
elif [ -n "${BASH_VERSION}" ]; then
	# We are in bash - green time, cyan path, red git branch
	export PS1="\[\033[32m\]\t\[\033[00m\] \[\033[38;5;39m\]\w\[\033[00m\]\[\033[31m\]\$(git_branch)\[\033[00m\] $ "
else
	# Not in bash or zsh
	echo "We are not in a bash"
fi
